### ISSUE TITLE
Filename Extensions

### ISSUE THREAD

**Issue by cyberdork33** [suminb/readown#2]
This issue was at the google code site:
http://code.google.com/p/readown/issues/detail?id=3

Would really like to see Readown not restricted to specific filename extensions. I have also had *.mdtext files that cannot be opened, but are rendered perfectly the the extension is changed.

**Comment by suminb** [comment]
I just posted a new version on the [download page](https://github.com/suminb/readown/downloads). Please let me know if this issue persists.

**Comment by dahlia** [comment]
:+1:

**Comment by cyberdork33** [comment]
I've tried the new version on two machines (Lion) and it just immediately crashes.

**Comment by suminb** [comment]
I built it with Xcode 4.5 (developer preview), and tested on Mac OS X 10.8.1 (Mountain Lion). I'll try to run it on my MacBook (with OSX 10.7.4 installed) to see what happens later this afternoon. Thanks for your feedback.

**Comment by suminb** [comment]
I just confirmed that it immediately crashes on launch on OSX 10.7.4.

**Comment by suminb** [comment]
OK. Finally. I have built it on my MacBook with OSX 10.7.4 (Lion). Please let me know if it still crashes. You can download the file from the exactly [same link](https://github.com/suminb/readown/downloads).

**Comment by cyberdork33** [comment]
looks good!
