### ISSUE TITLE
Distribute Readown on Mac App Store

### ISSUE THREAD

**Issue by dahlia** [suminb/readown#4]
Users would be able to install it more easily.

**Comment by suminb** [comment]
Good idea. But we're gonna have to get some donation to setup an Apple Mac developers account. I think it costs $99+tax per year.

**Comment by youknowone** [comment]
@suminb Hi. I suggest you a developer account. It is used to distribute https://github.com/xchataqua/xchataqua and https://github.com/youknowone/VisualJSON
