### ISSUE TITLE
README still refers to Google Code

### ISSUE THREAD

**Issue by ryandesign** [suminb/readown#9]
The README still refers users to the defunct Google Code service to download binaries or code even though the project moved to GitHub long ago:

https://github.com/suminb/readown/blob/ce422b13fb1ef4dc4544dbcc5082472a2a8b503c/README.markdown?plain=1#L11-L17

**Comment by suminb** [comment]
Thanks for your input. However, this project is no longer maintained and will be archived. Thanks again for your interest in project.
